### ISSUE TITLE
Loading fake data from json

### ISSUE THREAD

**Issue by MilesHart** [imanghafoori1/eloquent-mockery#15]
I have a data dependent testing, so I want to use a library of JSON files, what is the best way to load from a json file into a Fake model?

`$mockFileRaw = file_get_contents(__DIR__ . "/../testdata/ruleMock1.json");

$objMock = json_decode($mockFileRaw);

Rule::fake();

$rule = Rule::create($objMock);`

Any help would be appreciated.

**Comment by imanghafoori1** [comment]
I am planning to add a feature for loading the initial data from config like php files.
currently, you can loop through your data and use the `FakeDB::addRow(...)` method.

**Comment by MilesHart** [comment]
Thank you, much appreciated.
