### ISSUE TITLE
v1 branch

### ISSUE THREAD

**Issue by ekvedaras** [imanghafoori1/eloquent-mockery#24]
Hi, thanks for the package 👍 

Could you create a branch from [`v1.0.40`](https://github.com/imanghafoori1/eloquent-mockery/releases/tag/v1.0.40) tag so we could open PRs for fixes in `v1` ? :) I see there are a lot of unreleased commits in `main` with significant refactoring, so we need a way to improve the existing version until that is ready to be released.

**Comment by imanghafoori1** [comment]
Hi
I am curious about your problem and why you do not use the dev-main branch.

**Comment by ekvedaras** [comment]
`dev-main` is untagged, unstable and not recommended. That is why we have tags and [semantic versioning](https://getcomposer.org/doc/articles/versions.md). We're currently at `v1.0.40` which is the latest stable version of this package. There have been many commits made after this tag, but no release and I suspect it is not coming soon 🤔 

This package (or at least the version of it tagged at `1.0.40`) is built with the assumption of auto-incrementing IDs. This fails in certain cases when UUIDs are used. Would like to try to implement a "fix" so it could be released as `v1.0.41` but that now is not possible because `main` branch has breaking changes and would need to be `v2.x`. If we have `v1` branch we can push fixes to it and tag `v1.0.41` on that branch. Thus `main` branch can continue to evolve and v1 support can continue independently until `v2` is released.

**Comment by imanghafoori1** [comment]
Anyways I recommend using dev-main version. I thought no one will use this until make it was ready.
Ok, I will release version 1.x in a few days.

**Comment by ekvedaras** [comment]
The speed gains are too good not to use 😃 But 1x (1.0.40) is already released? 🤔 Is that by mistake or you mean you will create V1 branch? 🙂

**Comment by imanghafoori1** [comment]
I do not remember anything along the 1.x 
all of them should be 0.1.x
If you see 1.x or something, it is by mistype.  😃

**Comment by ekvedaras** [comment]
Ok that explains it 😃 So yeah there is a 1.0.40 tag by mistake then 🙂

**Comment by imanghafoori1** [comment]
I removed that release on packagist.org, I think should not see it anymore.
Thanks for the report.

This package basically should support migrations so that the fake DB should gain some insights about the default values of columns and type of IDs and etc.

**Comment by ekvedaras** [comment]
I suspect this will break some people's installs once the cache is gone from packagist as it was the default version install when you run `composer require imanghafoori/eloquent-mockery` 😄 I'll update our project 🙂

**Comment by ekvedaras** [comment]
> This package basically should support migrations so that the fake DB should gain some insights about the default values of columns and type of IDs and etc.

Maybe, but I still saw places where it does `($lastInsertId ?? 0) + 1` which does not work when that ID is not int :)

**Comment by imanghafoori1** [comment]
I have a lot of changes and features in mind but this heavy project makes me no money and I am also involved with the laravel-micoscope as well. Anyways it was exciting to see that my work is getting used without getting fully ready or advertised.
Makes me motivated to finish it.
